/**

Generated by the following Solidity interface...
```solidity
interface IERC20LiquidationBot {
    function coreCallback(address _sender, bytes memory _data) external payable returns (bytes memory result);
    function flashLiquidate(uint256 _posId, address _poolToBorrow, address _router, address _poolToRepay, address _router2, address _poolOut, uint256 _minAmtOut) external;
    function flashLiquidateReturnNative(uint256 _posId, address _poolToBorrow, address _router, address _poolToRepay, address _router2, address _poolOut, address _router3, uint256 _minAmtOut) external;
    function getLiquidationInfo(uint256 _posId) external returns (address bestPoolToRepay, address bestPoolOut, uint256 maxRepayAmt);
    function getMaxRepayAmt(uint256 _posId, address _poolToRepay, address _poolOut) external returns (address repayToken, uint256 maxRepayAmt);
}
```

...which was generated by the following JSON ABI:
```json
[
  {
    "type": "function",
    "name": "coreCallback",
    "inputs": [
      {
        "name": "_sender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "result",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "flashLiquidate",
    "inputs": [
      {
        "name": "_posId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_poolToBorrow",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_router",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_poolToRepay",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_router2",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_poolOut",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_minAmtOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "flashLiquidateReturnNative",
    "inputs": [
      {
        "name": "_posId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_poolToBorrow",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_router",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_poolToRepay",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_router2",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_poolOut",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_router3",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_minAmtOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getLiquidationInfo",
    "inputs": [
      {
        "name": "_posId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "bestPoolToRepay",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "bestPoolOut",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "maxRepayAmt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getMaxRepayAmt",
    "inputs": [
      {
        "name": "_posId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_poolToRepay",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_poolOut",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "repayToken",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "maxRepayAmt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  }
]
```*/
#[allow(
    non_camel_case_types,
    non_snake_case,
    clippy::pub_underscore_fields,
    clippy::style,
    clippy::empty_structs_with_brackets
)]
pub mod IERC20LiquidationBot {
    use super::*;
    use alloy::sol_types as alloy_sol_types;
    /// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"",
    );
    /// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"",
    );
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `coreCallback(address,bytes)` and selector `0x8a839fde`.
```solidity
function coreCallback(address _sender, bytes memory _data) external payable returns (bytes memory result);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct coreCallbackCall {
        #[allow(missing_docs)]
        pub _sender: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _data: alloy::sol_types::private::Bytes,
    }
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`coreCallback(address,bytes)`](coreCallbackCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct coreCallbackReturn {
        #[allow(missing_docs)]
        pub result: alloy::sol_types::private::Bytes,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Bytes,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Bytes,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<coreCallbackCall> for UnderlyingRustTuple<'_> {
                fn from(value: coreCallbackCall) -> Self {
                    (value._sender, value._data)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for coreCallbackCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        _sender: tuple.0,
                        _data: tuple.1,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::Bytes,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (alloy::sol_types::private::Bytes,);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<coreCallbackReturn> for UnderlyingRustTuple<'_> {
                fn from(value: coreCallbackReturn) -> Self {
                    (value.result,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for coreCallbackReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { result: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for coreCallbackCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Bytes,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = coreCallbackReturn;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::Bytes,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "coreCallback(address,bytes)";
            const SELECTOR: [u8; 4] = [138u8, 131u8, 159u8, 222u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._sender,
                    ),
                    <alloy::sol_types::sol_data::Bytes as alloy_sol_types::SolType>::tokenize(
                        &self._data,
                    ),
                )
            }
            #[inline]
            fn abi_decode_returns(
                data: &[u8],
                validate: bool,
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data, validate)
                    .map(Into::into)
            }
        }
    };
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `flashLiquidate(uint256,address,address,address,address,address,uint256)` and selector `0x304c9e6e`.
```solidity
function flashLiquidate(uint256 _posId, address _poolToBorrow, address _router, address _poolToRepay, address _router2, address _poolOut, uint256 _minAmtOut) external;
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct flashLiquidateCall {
        #[allow(missing_docs)]
        pub _posId: alloy::sol_types::private::primitives::aliases::U256,
        #[allow(missing_docs)]
        pub _poolToBorrow: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _router: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _poolToRepay: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _router2: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _poolOut: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _minAmtOut: alloy::sol_types::private::primitives::aliases::U256,
    }
    ///Container type for the return parameters of the [`flashLiquidate(uint256,address,address,address,address,address,uint256)`](flashLiquidateCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct flashLiquidateReturn {}
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<256>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::primitives::aliases::U256,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<flashLiquidateCall> for UnderlyingRustTuple<'_> {
                fn from(value: flashLiquidateCall) -> Self {
                    (
                        value._posId,
                        value._poolToBorrow,
                        value._router,
                        value._poolToRepay,
                        value._router2,
                        value._poolOut,
                        value._minAmtOut,
                    )
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for flashLiquidateCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        _posId: tuple.0,
                        _poolToBorrow: tuple.1,
                        _router: tuple.2,
                        _poolToRepay: tuple.3,
                        _router2: tuple.4,
                        _poolOut: tuple.5,
                        _minAmtOut: tuple.6,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = ();
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = ();
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<flashLiquidateReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: flashLiquidateReturn) -> Self {
                    ()
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for flashLiquidateReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {}
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for flashLiquidateCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<256>,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = flashLiquidateReturn;
            type ReturnTuple<'a> = ();
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "flashLiquidate(uint256,address,address,address,address,address,uint256)";
            const SELECTOR: [u8; 4] = [48u8, 76u8, 158u8, 110u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(&self._posId),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._poolToBorrow,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._router,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._poolToRepay,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._router2,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._poolOut,
                    ),
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(&self._minAmtOut),
                )
            }
            #[inline]
            fn abi_decode_returns(
                data: &[u8],
                validate: bool,
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data, validate)
                    .map(Into::into)
            }
        }
    };
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `flashLiquidateReturnNative(uint256,address,address,address,address,address,address,uint256)` and selector `0x14f7ee26`.
```solidity
function flashLiquidateReturnNative(uint256 _posId, address _poolToBorrow, address _router, address _poolToRepay, address _router2, address _poolOut, address _router3, uint256 _minAmtOut) external;
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct flashLiquidateReturnNativeCall {
        #[allow(missing_docs)]
        pub _posId: alloy::sol_types::private::primitives::aliases::U256,
        #[allow(missing_docs)]
        pub _poolToBorrow: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _router: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _poolToRepay: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _router2: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _poolOut: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _router3: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _minAmtOut: alloy::sol_types::private::primitives::aliases::U256,
    }
    ///Container type for the return parameters of the [`flashLiquidateReturnNative(uint256,address,address,address,address,address,address,uint256)`](flashLiquidateReturnNativeCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct flashLiquidateReturnNativeReturn {}
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<256>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::primitives::aliases::U256,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<flashLiquidateReturnNativeCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: flashLiquidateReturnNativeCall) -> Self {
                    (
                        value._posId,
                        value._poolToBorrow,
                        value._router,
                        value._poolToRepay,
                        value._router2,
                        value._poolOut,
                        value._router3,
                        value._minAmtOut,
                    )
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for flashLiquidateReturnNativeCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        _posId: tuple.0,
                        _poolToBorrow: tuple.1,
                        _router: tuple.2,
                        _poolToRepay: tuple.3,
                        _router2: tuple.4,
                        _poolOut: tuple.5,
                        _router3: tuple.6,
                        _minAmtOut: tuple.7,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = ();
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = ();
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<flashLiquidateReturnNativeReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: flashLiquidateReturnNativeReturn) -> Self {
                    ()
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for flashLiquidateReturnNativeReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {}
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for flashLiquidateReturnNativeCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<256>,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = flashLiquidateReturnNativeReturn;
            type ReturnTuple<'a> = ();
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "flashLiquidateReturnNative(uint256,address,address,address,address,address,address,uint256)";
            const SELECTOR: [u8; 4] = [20u8, 247u8, 238u8, 38u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(&self._posId),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._poolToBorrow,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._router,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._poolToRepay,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._router2,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._poolOut,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._router3,
                    ),
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(&self._minAmtOut),
                )
            }
            #[inline]
            fn abi_decode_returns(
                data: &[u8],
                validate: bool,
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data, validate)
                    .map(Into::into)
            }
        }
    };
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `getLiquidationInfo(uint256)` and selector `0x50ef5c35`.
```solidity
function getLiquidationInfo(uint256 _posId) external returns (address bestPoolToRepay, address bestPoolOut, uint256 maxRepayAmt);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getLiquidationInfoCall {
        #[allow(missing_docs)]
        pub _posId: alloy::sol_types::private::primitives::aliases::U256,
    }
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`getLiquidationInfo(uint256)`](getLiquidationInfoCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getLiquidationInfoReturn {
        #[allow(missing_docs)]
        pub bestPoolToRepay: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub bestPoolOut: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub maxRepayAmt: alloy::sol_types::private::primitives::aliases::U256,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getLiquidationInfoCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: getLiquidationInfoCall) -> Self {
                    (value._posId,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for getLiquidationInfoCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { _posId: tuple.0 }
                }
            }
        }
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<256>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getLiquidationInfoReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: getLiquidationInfoReturn) -> Self {
                    (value.bestPoolToRepay, value.bestPoolOut, value.maxRepayAmt)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for getLiquidationInfoReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        bestPoolToRepay: tuple.0,
                        bestPoolOut: tuple.1,
                        maxRepayAmt: tuple.2,
                    }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for getLiquidationInfoCall {
            type Parameters<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = getLiquidationInfoReturn;
            type ReturnTuple<'a> = (
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<256>,
            );
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "getLiquidationInfo(uint256)";
            const SELECTOR: [u8; 4] = [80u8, 239u8, 92u8, 53u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(&self._posId),
                )
            }
            #[inline]
            fn abi_decode_returns(
                data: &[u8],
                validate: bool,
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data, validate)
                    .map(Into::into)
            }
        }
    };
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `getMaxRepayAmt(uint256,address,address)` and selector `0x53d90816`.
```solidity
function getMaxRepayAmt(uint256 _posId, address _poolToRepay, address _poolOut) external returns (address repayToken, uint256 maxRepayAmt);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getMaxRepayAmtCall {
        #[allow(missing_docs)]
        pub _posId: alloy::sol_types::private::primitives::aliases::U256,
        #[allow(missing_docs)]
        pub _poolToRepay: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _poolOut: alloy::sol_types::private::Address,
    }
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`getMaxRepayAmt(uint256,address,address)`](getMaxRepayAmtCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getMaxRepayAmtReturn {
        #[allow(missing_docs)]
        pub repayToken: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub maxRepayAmt: alloy::sol_types::private::primitives::aliases::U256,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::primitives::aliases::U256,
                alloy::sol_types::private::Address,
                alloy::sol_types::private::Address,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getMaxRepayAmtCall> for UnderlyingRustTuple<'_> {
                fn from(value: getMaxRepayAmtCall) -> Self {
                    (value._posId, value._poolToRepay, value._poolOut)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for getMaxRepayAmtCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        _posId: tuple.0,
                        _poolToRepay: tuple.1,
                        _poolOut: tuple.2,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<256>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::Address,
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getMaxRepayAmtReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: getMaxRepayAmtReturn) -> Self {
                    (value.repayToken, value.maxRepayAmt)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for getMaxRepayAmtReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        repayToken: tuple.0,
                        maxRepayAmt: tuple.1,
                    }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for getMaxRepayAmtCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Address,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = getMaxRepayAmtReturn;
            type ReturnTuple<'a> = (
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<256>,
            );
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "getMaxRepayAmt(uint256,address,address)";
            const SELECTOR: [u8; 4] = [83u8, 217u8, 8u8, 22u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(&self._posId),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._poolToRepay,
                    ),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._poolOut,
                    ),
                )
            }
            #[inline]
            fn abi_decode_returns(
                data: &[u8],
                validate: bool,
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data, validate)
                    .map(Into::into)
            }
        }
    };
    ///Container for all the [`IERC20LiquidationBot`](self) function calls.
    #[derive()]
    pub enum IERC20LiquidationBotCalls {
        #[allow(missing_docs)]
        coreCallback(coreCallbackCall),
        #[allow(missing_docs)]
        flashLiquidate(flashLiquidateCall),
        #[allow(missing_docs)]
        flashLiquidateReturnNative(flashLiquidateReturnNativeCall),
        #[allow(missing_docs)]
        getLiquidationInfo(getLiquidationInfoCall),
        #[allow(missing_docs)]
        getMaxRepayAmt(getMaxRepayAmtCall),
    }
    #[automatically_derived]
    impl IERC20LiquidationBotCalls {
        /// All the selectors of this enum.
        ///
        /// Note that the selectors might not be in the same order as the variants.
        /// No guarantees are made about the order of the selectors.
        ///
        /// Prefer using `SolInterface` methods instead.
        pub const SELECTORS: &'static [[u8; 4usize]] = &[
            [20u8, 247u8, 238u8, 38u8],
            [48u8, 76u8, 158u8, 110u8],
            [80u8, 239u8, 92u8, 53u8],
            [83u8, 217u8, 8u8, 22u8],
            [138u8, 131u8, 159u8, 222u8],
        ];
    }
    #[automatically_derived]
    impl alloy_sol_types::SolInterface for IERC20LiquidationBotCalls {
        const NAME: &'static str = "IERC20LiquidationBotCalls";
        const MIN_DATA_LENGTH: usize = 32usize;
        const COUNT: usize = 5usize;
        #[inline]
        fn selector(&self) -> [u8; 4] {
            match self {
                Self::coreCallback(_) => {
                    <coreCallbackCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::flashLiquidate(_) => {
                    <flashLiquidateCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::flashLiquidateReturnNative(_) => {
                    <flashLiquidateReturnNativeCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::getLiquidationInfo(_) => {
                    <getLiquidationInfoCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::getMaxRepayAmt(_) => {
                    <getMaxRepayAmtCall as alloy_sol_types::SolCall>::SELECTOR
                }
            }
        }
        #[inline]
        fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
            Self::SELECTORS.get(i).copied()
        }
        #[inline]
        fn valid_selector(selector: [u8; 4]) -> bool {
            Self::SELECTORS.binary_search(&selector).is_ok()
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw(
            selector: [u8; 4],
            data: &[u8],
            validate: bool,
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_SHIMS: &[fn(
                &[u8],
                bool,
            ) -> alloy_sol_types::Result<IERC20LiquidationBotCalls>] = &[
                {
                    fn flashLiquidateReturnNative(
                        data: &[u8],
                        validate: bool,
                    ) -> alloy_sol_types::Result<IERC20LiquidationBotCalls> {
                        <flashLiquidateReturnNativeCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                                validate,
                            )
                            .map(IERC20LiquidationBotCalls::flashLiquidateReturnNative)
                    }
                    flashLiquidateReturnNative
                },
                {
                    fn flashLiquidate(
                        data: &[u8],
                        validate: bool,
                    ) -> alloy_sol_types::Result<IERC20LiquidationBotCalls> {
                        <flashLiquidateCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                                validate,
                            )
                            .map(IERC20LiquidationBotCalls::flashLiquidate)
                    }
                    flashLiquidate
                },
                {
                    fn getLiquidationInfo(
                        data: &[u8],
                        validate: bool,
                    ) -> alloy_sol_types::Result<IERC20LiquidationBotCalls> {
                        <getLiquidationInfoCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                                validate,
                            )
                            .map(IERC20LiquidationBotCalls::getLiquidationInfo)
                    }
                    getLiquidationInfo
                },
                {
                    fn getMaxRepayAmt(
                        data: &[u8],
                        validate: bool,
                    ) -> alloy_sol_types::Result<IERC20LiquidationBotCalls> {
                        <getMaxRepayAmtCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                                validate,
                            )
                            .map(IERC20LiquidationBotCalls::getMaxRepayAmt)
                    }
                    getMaxRepayAmt
                },
                {
                    fn coreCallback(
                        data: &[u8],
                        validate: bool,
                    ) -> alloy_sol_types::Result<IERC20LiquidationBotCalls> {
                        <coreCallbackCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                                validate,
                            )
                            .map(IERC20LiquidationBotCalls::coreCallback)
                    }
                    coreCallback
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(
                    alloy_sol_types::Error::unknown_selector(
                        <Self as alloy_sol_types::SolInterface>::NAME,
                        selector,
                    ),
                );
            };
            DECODE_SHIMS[idx](data, validate)
        }
        #[inline]
        fn abi_encoded_size(&self) -> usize {
            match self {
                Self::coreCallback(inner) => {
                    <coreCallbackCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::flashLiquidate(inner) => {
                    <flashLiquidateCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::flashLiquidateReturnNative(inner) => {
                    <flashLiquidateReturnNativeCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::getLiquidationInfo(inner) => {
                    <getLiquidationInfoCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::getMaxRepayAmt(inner) => {
                    <getMaxRepayAmtCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
            }
        }
        #[inline]
        fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
            match self {
                Self::coreCallback(inner) => {
                    <coreCallbackCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::flashLiquidate(inner) => {
                    <flashLiquidateCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::flashLiquidateReturnNative(inner) => {
                    <flashLiquidateReturnNativeCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::getLiquidationInfo(inner) => {
                    <getLiquidationInfoCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::getMaxRepayAmt(inner) => {
                    <getMaxRepayAmtCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
            }
        }
    }
    use alloy::contract as alloy_contract;
    /**Creates a new wrapper around an on-chain [`IERC20LiquidationBot`](self) contract instance.

See the [wrapper's documentation](`IERC20LiquidationBotInstance`) for more details.*/
    #[inline]
    pub const fn new<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    >(
        address: alloy_sol_types::private::Address,
        provider: P,
    ) -> IERC20LiquidationBotInstance<T, P, N> {
        IERC20LiquidationBotInstance::<T, P, N>::new(address, provider)
    }
    /**Deploys this contract using the given `provider` and constructor arguments, if any.

Returns a new instance of the contract, if the deployment was successful.

For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
    #[inline]
    pub fn deploy<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    >(
        provider: P,
    ) -> impl ::core::future::Future<
        Output = alloy_contract::Result<IERC20LiquidationBotInstance<T, P, N>>,
    > {
        IERC20LiquidationBotInstance::<T, P, N>::deploy(provider)
    }
    /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
and constructor arguments, if any.

This is a simple wrapper around creating a `RawCallBuilder` with the data set to
the bytecode concatenated with the constructor's ABI-encoded arguments.*/
    #[inline]
    pub fn deploy_builder<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    >(provider: P) -> alloy_contract::RawCallBuilder<T, P, N> {
        IERC20LiquidationBotInstance::<T, P, N>::deploy_builder(provider)
    }
    /**A [`IERC20LiquidationBot`](self) instance.

Contains type-safe methods for interacting with an on-chain instance of the
[`IERC20LiquidationBot`](self) contract located at a given `address`, using a given
provider `P`.

If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
documentation on how to provide it), the `deploy` and `deploy_builder` methods can
be used to deploy a new instance of the contract.

See the [module-level documentation](self) for all the available methods.*/
    #[derive(Clone)]
    pub struct IERC20LiquidationBotInstance<
        T,
        P,
        N = alloy_contract::private::Ethereum,
    > {
        address: alloy_sol_types::private::Address,
        provider: P,
        _network_transport: ::core::marker::PhantomData<(N, T)>,
    }
    #[automatically_derived]
    impl<T, P, N> ::core::fmt::Debug for IERC20LiquidationBotInstance<T, P, N> {
        #[inline]
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_tuple("IERC20LiquidationBotInstance").field(&self.address).finish()
        }
    }
    /// Instantiation and getters/setters.
    #[automatically_derived]
    impl<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    > IERC20LiquidationBotInstance<T, P, N> {
        /**Creates a new wrapper around an on-chain [`IERC20LiquidationBot`](self) contract instance.

See the [wrapper's documentation](`IERC20LiquidationBotInstance`) for more details.*/
        #[inline]
        pub const fn new(
            address: alloy_sol_types::private::Address,
            provider: P,
        ) -> Self {
            Self {
                address,
                provider,
                _network_transport: ::core::marker::PhantomData,
            }
        }
        /**Deploys this contract using the given `provider` and constructor arguments, if any.

Returns a new instance of the contract, if the deployment was successful.

For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
        #[inline]
        pub async fn deploy(
            provider: P,
        ) -> alloy_contract::Result<IERC20LiquidationBotInstance<T, P, N>> {
            let call_builder = Self::deploy_builder(provider);
            let contract_address = call_builder.deploy().await?;
            Ok(Self::new(contract_address, call_builder.provider))
        }
        /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
and constructor arguments, if any.

This is a simple wrapper around creating a `RawCallBuilder` with the data set to
the bytecode concatenated with the constructor's ABI-encoded arguments.*/
        #[inline]
        pub fn deploy_builder(provider: P) -> alloy_contract::RawCallBuilder<T, P, N> {
            alloy_contract::RawCallBuilder::new_raw_deploy(
                provider,
                ::core::clone::Clone::clone(&BYTECODE),
            )
        }
        /// Returns a reference to the address.
        #[inline]
        pub const fn address(&self) -> &alloy_sol_types::private::Address {
            &self.address
        }
        /// Sets the address.
        #[inline]
        pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
            self.address = address;
        }
        /// Sets the address and returns `self`.
        pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
            self.set_address(address);
            self
        }
        /// Returns a reference to the provider.
        #[inline]
        pub const fn provider(&self) -> &P {
            &self.provider
        }
    }
    impl<T, P: ::core::clone::Clone, N> IERC20LiquidationBotInstance<T, &P, N> {
        /// Clones the provider and returns a new instance with the cloned provider.
        #[inline]
        pub fn with_cloned_provider(self) -> IERC20LiquidationBotInstance<T, P, N> {
            IERC20LiquidationBotInstance {
                address: self.address,
                provider: ::core::clone::Clone::clone(&self.provider),
                _network_transport: ::core::marker::PhantomData,
            }
        }
    }
    /// Function calls.
    #[automatically_derived]
    impl<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    > IERC20LiquidationBotInstance<T, P, N> {
        /// Creates a new call builder using this contract instance's provider and address.
        ///
        /// Note that the call can be any function call, not just those defined in this
        /// contract. Prefer using the other methods for building type-safe contract calls.
        pub fn call_builder<C: alloy_sol_types::SolCall>(
            &self,
            call: &C,
        ) -> alloy_contract::SolCallBuilder<T, &P, C, N> {
            alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
        }
        ///Creates a new call builder for the [`coreCallback`] function.
        pub fn coreCallback(
            &self,
            _sender: alloy::sol_types::private::Address,
            _data: alloy::sol_types::private::Bytes,
        ) -> alloy_contract::SolCallBuilder<T, &P, coreCallbackCall, N> {
            self.call_builder(&coreCallbackCall { _sender, _data })
        }
        ///Creates a new call builder for the [`flashLiquidate`] function.
        pub fn flashLiquidate(
            &self,
            _posId: alloy::sol_types::private::primitives::aliases::U256,
            _poolToBorrow: alloy::sol_types::private::Address,
            _router: alloy::sol_types::private::Address,
            _poolToRepay: alloy::sol_types::private::Address,
            _router2: alloy::sol_types::private::Address,
            _poolOut: alloy::sol_types::private::Address,
            _minAmtOut: alloy::sol_types::private::primitives::aliases::U256,
        ) -> alloy_contract::SolCallBuilder<T, &P, flashLiquidateCall, N> {
            self.call_builder(
                &flashLiquidateCall {
                    _posId,
                    _poolToBorrow,
                    _router,
                    _poolToRepay,
                    _router2,
                    _poolOut,
                    _minAmtOut,
                },
            )
        }
        ///Creates a new call builder for the [`flashLiquidateReturnNative`] function.
        pub fn flashLiquidateReturnNative(
            &self,
            _posId: alloy::sol_types::private::primitives::aliases::U256,
            _poolToBorrow: alloy::sol_types::private::Address,
            _router: alloy::sol_types::private::Address,
            _poolToRepay: alloy::sol_types::private::Address,
            _router2: alloy::sol_types::private::Address,
            _poolOut: alloy::sol_types::private::Address,
            _router3: alloy::sol_types::private::Address,
            _minAmtOut: alloy::sol_types::private::primitives::aliases::U256,
        ) -> alloy_contract::SolCallBuilder<T, &P, flashLiquidateReturnNativeCall, N> {
            self.call_builder(
                &flashLiquidateReturnNativeCall {
                    _posId,
                    _poolToBorrow,
                    _router,
                    _poolToRepay,
                    _router2,
                    _poolOut,
                    _router3,
                    _minAmtOut,
                },
            )
        }
        ///Creates a new call builder for the [`getLiquidationInfo`] function.
        pub fn getLiquidationInfo(
            &self,
            _posId: alloy::sol_types::private::primitives::aliases::U256,
        ) -> alloy_contract::SolCallBuilder<T, &P, getLiquidationInfoCall, N> {
            self.call_builder(&getLiquidationInfoCall { _posId })
        }
        ///Creates a new call builder for the [`getMaxRepayAmt`] function.
        pub fn getMaxRepayAmt(
            &self,
            _posId: alloy::sol_types::private::primitives::aliases::U256,
            _poolToRepay: alloy::sol_types::private::Address,
            _poolOut: alloy::sol_types::private::Address,
        ) -> alloy_contract::SolCallBuilder<T, &P, getMaxRepayAmtCall, N> {
            self.call_builder(
                &getMaxRepayAmtCall {
                    _posId,
                    _poolToRepay,
                    _poolOut,
                },
            )
        }
    }
    /// Event filters.
    #[automatically_derived]
    impl<
        T: alloy_contract::private::Transport + ::core::clone::Clone,
        P: alloy_contract::private::Provider<T, N>,
        N: alloy_contract::private::Network,
    > IERC20LiquidationBotInstance<T, P, N> {
        /// Creates a new event filter using this contract instance's provider and address.
        ///
        /// Note that the type can be any event, not just those defined in this contract.
        /// Prefer using the other methods for building type-safe event filters.
        pub fn event_filter<E: alloy_sol_types::SolEvent>(
            &self,
        ) -> alloy_contract::Event<T, &P, E, N> {
            alloy_contract::Event::new_sol(&self.provider, &self.address)
        }
    }
}
